### ISSUE TITLE
1.18 ？

### ISSUE THREAD

**Issue by TexBlock** [LukeGrahamLandry/ForgedFabric#1]
1.19 and 1.16 are available but what about 1.18?

**Comment by LukeGrahamLandry** [comment]
there's a branch for it but the library doesn't achieve anything without mods that depend on it. at the moment the mods I'm working on are in 1.16.5 but if someone commissions a forge port of any fabric 1.18 mods I'll bring the 1.18 branch up to feature parity and whatever else I need to complete that project. PRs are welcome if you have a different priority :)
