### ISSUE TITLE
ForgedFabric crashing with better combat and playeranimationlib on startup

### ISSUE THREAD

**Issue by monkeygamer123** [LukeGrahamLandry/ForgedFabric#3]
So I downloaded ForgedFabric-0.05-1.16.5, the 1.16 better combat port, and playeranimationlib. When i dragged these into the mods folder and tried to start it up, minecraft crashed with Exit code 1. I tried everything i could, but nothing worked. Can you help me out here?

**Comment by LukeGrahamLandry** [comment]
This doesn’t give enough information for me to say anything useful. If you send the latest.log file that contains the actual crash message, I can take a look.

**Comment by ghost** [comment]
Same issue here, I'm running a relatively small instance with only performance mods so far, but adding those 3 mods results in a crash. Here's my latest log: https://gist.github.com/Puffadillo/3ff489135d1067ea9bf26117747b7387

**Comment by monkeygamer123** [comment]
Here is the latest.log file - 
[latest.log-2.txt](https://github.com/LukeGrahamLandry/ForgedFabric/files/10949770/latest.log-2.txt)



The only other mod I added with these mods is Optifine.
I hope this helps.

**Comment by LukeGrahamLandry** [comment]
hmm, looks like you didnt have Cloth Config installed
